spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/playspot
    username: youruser
    password: yourpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: VerySecretKey1234567890
  expiration: 3600000
  refresh-expiration: 86400000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: profile, email
